---
title: "Course contents"
---

This course is based on [Modèles hiérarchiques pour les sciences de la vie](https://bios2.github.io/hiermod/) by Guillaume Blanchet and Andrew MacDonald.

## Day 1: Introduction, data simulation, discrete models

:::: {.columns}

::: {.column width="50%"}

### Slides
* [Bayesian and MCMC](slides/02_Bayesian)
* [Stan and HMC](slides/03_Stan)
* [Probability Distributions](slides/02_5_Distribution)

:::


::: {.column width="50%"}
### Exercises
* [Simulation and model fitting in Stan](topics/01_simulation)
:::

::::

## Day 2

:::: {.columns}

::: {.column width="50%"}

### Slides
* [Data we'll be using](slides/01_Data)
* [Linear models](slides/04_Linear_model)

:::


::: {.column width="50%"}
### Exercises
* [Discrete predictors](topics/discrete_predictor)
* [Linear regression](topics/02_regression)
:::

::::

## Day 3

:::: {.columns}

::: {.column width="50%"}
### Slides
* [Simple hierarchical models](slides/06_Simple_hierarchical_model)

:::

::: {.column width="50%"}
### Exercises


* [Hierarchy on the intercept](topics/03_one_random_effect)
<!-- * [Hierarchy on the slope](topics/correlated_effects) -->

:::

::::


## Day 4

:::: {.columns}

::: {.column width="50%"}
### Slides
* [Complex hierarchical models](slides/08_Complex_hierarchical_model)

:::

::: {.column width="50%"}
### Exercises


* [Hierarchy on the intercept](topics/03_one_random_effect)
* [offsets](topics/06_offsets)
* [Intercept-Only Model](topics/intercept_only)
* [Hierarchy on the slope](topics/correlated_effects)

:::

::::

<!--

## DAY 2: Understanding, Fitting, and Evaluating Random Intercept Models

Session 4 - 01:15:00 - Introduction to brms
Overview of the brms package; Stan as backend; model formula syntax, specifying families and priors; fitting basic models with brm().
Session 5 - 01:15:00 - Bayesian GLMs for Ecologists
Fitting Poisson, Gaussian, and logistic models in brms; posterior summaries and interpretation; visualising fitted effects and posterior uncertainty.
Session 6 - 01:15:00 - Visualising and Summarising Models
Using bayesplot, ggplot2, and tidybayes to explore posterior distributions and posterior predictions.


:::: {.columns}

::: {.column width="50%"}
### Slides


:::


::::


## Day 3: Motivation, Implementation, and Evaluation of Random Intercept Models

Session 7 - 01:15:00 - Why Multilevel Models?
Introducing Pseudo-replication and non-independence in ecological data; random intercepts and partial pooling; visualising multilevel model structure.
Session 8 - 01:15:00 - Fitting Random Intercepts in brms
Syntax for random effects in brms; interpreting group-level effects and variance components; extracting and plotting random intercepts.
Session 9 - 01:15:00 - Model Diagnostics for Multilevel Models
Examining traceplots, convergence checks, posterior predictive checks by group; assessing fit and structure of random intercept models.



## Day 4: Random Slopes, Model Structures, and Predictor Preparation in Multilevel Models

Session 10 - 01:15:00 - Random Slopes and Slope and Intercept Models
Motivation for random slopes, syntax and interpretation, understanding and visualising intercept-slope correlations.
Session 11 - 01:15:00 - Crossed vs. Nested Random Effects
Conceptual and practical distinctions between nested and crossed designs; specifying models in brms; ecological use cases and implications.
Session 12 - 01:15:00 - Centring and Scaling Predictors
Grand mean vs. group mean centring; standardisation for model convergence and interpretation; coding and plotting strategies.

:::: {.columns}

::: {.column width="50%"}

* [Slides](slides/09_Gaussian_process)

:::

::: {.column width="50%"}
* [A Practical demonstration in Stan](topics/04_gp)
* [Phylogeny](topics/04-phylo)
:::

::::


## Day 5 GLMMs for Ecological Data – Discrete Outcomes and Model Fit Assessment

Session 13 - 01:15:00 - Extending Count Models: overdispersion Poisson models with observation-level random effects, Negative Binomial models, and Zero-Inflated models.
Modelling count data in ecology; overdispersion and zero inflation; comparing Poisson and NB models. Overdispersion in proportion models, using the beta-binomial model. ; fitting ZIP/ZINB models in brms.
Session 14 - 01:15:00 - Binary and Proportional Data  – accounting for unequal sampling effort
Bernoulli and binomial models; grouped trials and proportion data; predicting and visualising probabilities; accounting for random effects.
Session 15 - 01:15:00 - Posterior Predictive Checks for GLMMs
Assessing model fit; using bayes_R2(), LOO cross-validation, and residual plots to evaluate model performance.

-->